- name: Merge Repositories
  run: |
    git clone --depth 1 https://github.com/VIDHEESH/portfolio.git temp
    mkdir -p WebDevelopment/Portfolio
    mv temp/* WebDevelopment/Portfolio/
    rm -rf temp
    git config --global user.email "vidheesh1@gmail.com"
    git config --global user.name "VIDHEESH"
    git add .
    git commit -m "Added Portfolio"
    git push origin main
  shell: bash
