name: Merge Repositories

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `Projects` repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Merge Capstone-Project-HTML Repository
        run: |
          git clone --depth 1 https://github.com/VIDHEESH/Capstone-Project-HTML.gittemp
          mkdir -p WebDevelopment/Capstone-Project-HTML
          mv temp/* WebDevelopment/Capstone-Project-HTML/
          rm -rf temp
          git config --global user.email "vidheesh1@gmail.com"
          git config --global user.name "VIDHEESH"
          git config --global credential.helper store
          echo "https://VIDHEESH:${{ secrets.GH_PAT }}@github.com" > ~/.git-credentials
          git add .
          git commit -m "Capstone-Project-HTML"
          git push https://VIDHEESH:${{ secrets.GH_PAT }}@github.com/VIDHEESH/Projects.git main
